#define PRINTS(x)  interrupt(33,0,x,0,0)
#define PRINTN(x)  interrupt(33,13,x,0,0)
#define LPRINTS(x) interrupt(33,0,x,1,0)
#define LPRINTN(x) interrupt(33,13,x,1,0)
#define SCANS(x)   interrupt(33,1,x,0,0)
#define SCANN(x)   interrupt(33,14,&x,0,0)
#define END        interrupt(33,5,0,0,0)
#define CLRSCRN(BACK, FORE)  interrupt(33,12,BACK,FORE,0)
#define BOOT() interrupt(33,11,0,0,0)
#define RM(FileName) interrupt(33, , &FileName,0,0)
#define ERROR(33, 2, 0,0,0)
#define WRITEFILE(FILENAME, TEXT) interrupt(
#define EXEC(FileName)
#define CREATEFILE(FILENAME)
#define READFILE(FILENAME)
#define REMOVEFILE(FILENAME)
		
